### Numpy Conti...

#### Random 
- It generates random values in a range

In [6]:
# Example of random.randint()
import numpy as np
r = np.random.randint(10)
print(r)

6


In [9]:
r = np.random.randint(10,40)
print(r)

19


In [12]:
r = np.random.randint(10,40,12)
print(r)
print(r.ndim)

[27 37 12 39 26 23 14 39 22 30 26 20]
1


In [13]:
r = np.random.randint(10,40,12).reshape(3,4)
print(r)

[[24 10 19 31]
 [38 39 33 12]
 [13 18 21 35]]


In [14]:
r = np.random.randint(10,40,12).reshape(1,3,4)
print(r)

[[[26 16 20 30]
  [30 13 20 18]
  [24 25 26 18]]]


In [15]:
r = np.random.randint(10,40,(5,4))
print(r)

[[17 12 16 26]
 [34 37 25 23]
 [28 36 23 37]
 [12 19 31 18]
 [24 20 35 33]]


In [16]:
r = np.random.randint(10,40,(1,5,4))
print(r)

[[[17 16 35 39]
  [35 22 10 35]
  [33 33 20 11]
  [22 16 10 34]
  [25 26 20 39]]]


In [18]:
# np.random.random(shape)
np.random.random() # It returns values in between 0 to 1

0.33404037411762166

In [19]:
np.random.random((2,3))

array([[0.5421567 , 0.85036487, 0.52198638],
       [0.49271844, 0.61836747, 0.33766735]])

In [20]:
# np.random.randn()
np.random.randn()

0.08685484018142405

In [21]:
np.random.randn(4,5)

array([[-1.05190684,  1.45165498,  1.02912917,  0.31152898, -3.39418353],
       [-1.27673751,  1.02670357,  1.67268144,  1.05342089, -0.44381042],
       [-0.74817058, -1.97539515, -0.10315215, -1.4880832 , -0.81463337],
       [ 0.3924141 ,  0.66418308,  0.15613085,  0.60334963, -0.51126592]])

In [22]:
np.random.normal()

-0.049520413202151094

In [25]:
np.random.normal(3,2)

4.180074804980268

In [26]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : fl

In [27]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [28]:
a1 = np.arange(11,20).reshape(3,3)
print(a1)
print("-----------")
a2 = np.arange(1,10).reshape(3,3)
print(a2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
-----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
# Arithmetic Operations
print(a1+a2)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [30]:
print(a1-a2)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [31]:
print(a1*a2)
print("-----------")
print(a1/a2)
print("-----------")
print(a1%a2)
print("-----------")
print(a1**a2)
print("-----------")

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
-----------
[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]
-----------
[[0 0 1]
 [2 0 4]
 [3 2 1]]
-----------
[[         11         144        2197]
 [      38416      759375    16777216]
 [  410338673 -1864941312   565150579]]
-----------


In [33]:
print(np.max(a1))
print(np.min(a1))

19
11


In [34]:
print(np.max(a2))
print(np.min(a2))

9
1


In [38]:
### Transpose Matrix
print(a1)
print("---------")
print(a1.T)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
---------
[[11 14 17]
 [12 15 18]
 [13 16 19]]


In [43]:
## Scientific Computation
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.power(5,1/2))
print(np.sqrt(144))

15.0
15.0
2.581988897471611
2.23606797749979
12.0


In [44]:
import math
math.sqrt(144)

12.0

In [45]:
import random

In [47]:
random.randint(10,20)

10

In [48]:
print(np.log(10))

2.302585092994046


In [49]:
print(np.exp(1))

2.718281828459045


In [50]:
import numpy as np

In [51]:
# vstack
a1 = np.arange(1,6)
print(a1)

[1 2 3 4 5]


In [52]:
print(np.vstack(a1))

[[1]
 [2]
 [3]
 [4]
 [5]]


In [53]:
print(np.hstack(a1))

[1 2 3 4 5]


In [55]:
print(np.vstack(a2))
print(np.hstack(a2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


### Accessing a particular element using indexing|slicing
- Syntax : [start:end,start:end] ---> [rows,columns]

In [58]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
print(a[0][0])
print(a[0][1])
print(a[4][4])

1
2
25


In [59]:
print(a[2][2])

13


In [ ]:
14, 15
19, 20
24, 25

In [60]:
print(a[2:,3:])

[[14 15]
 [19 20]
 [24 25]]


In [61]:
print(a[2:5,3:5])

[[14 15]
 [19 20]
 [24 25]]


## Pandas
- Stands for PanelData
- One of the data science library
- Used for data manipulation, analysis and cleaning
- It contains two data structures. such as
    1. Series
    2. DataFrames
    
- Series : is a sequence of data
- DataFrames : is a data with rows and columns

In [65]:
import pandas as pd

In [66]:
pd.__version__

'1.0.5'

In [67]:
# Creating data with series
# pd.Series([list of elements])

s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [68]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [69]:
pd.Series(a)

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [73]:
s = pd.Series(['a','b','k','e','r'],index=[5,4,2,3,1])
s

5    a
4    b
2    k
3    e
1    r
dtype: object

In [74]:
print(s[4])

b


In [76]:
s = pd.Series(['keerthi',221,7.0],index=['str','int','float'])
s

str      keerthi
int          221
float          7
dtype: object

In [77]:
s['int']

221

In [78]:
# Creating Data Series using Dictionary
dic = {'key1':'keerthi','key2':221,'key3':7.9}
pd.Series(dic)

key1    keerthi
key2        221
key3        7.9
dtype: object

In [79]:
dic = {'name':'keerthi','id':221,'g':7.9}
pd.Series(dic)

name    keerthi
id          221
g           7.9
dtype: object

In [80]:
# Creating Data Series using tuple
t = (1,2,3,4,5,6)
pd.Series(t,index=['a','b','c','d','e','f'])

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [82]:
s = pd.Series(np.random.randint(10,40,6),index=np.arange(1,7))
s

1    34
2    19
3    26
4    24
5    19
6    19
dtype: int32

In [83]:
s[6]='apssdc'
s

1        34
2        19
3        26
4        24
5        19
6    apssdc
dtype: object

In [84]:
print(dir(list))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


## DataFrames

In [86]:
# Creating Data using DataFrames
d = pd.DataFrame([1,2,3,4,5])
d

0
0  1
1  2
2  3
3  4
4  5

In [88]:
li = [[1,2,3],[2,3,8],[5,6,7]]
pd.DataFrame(li,index=['l1','l2','l3'])

0  1  2
l1  1  2  3
l2  2  3  8
l3  5  6  7

In [89]:
a = [['kalyan',12,8.7],['manikanta',34,9.0],['kavitha',15,9.7]]
data = pd.DataFrame(a,columns=('Names','Rollno','Grade'),index=np.arange(1,4))
data

Names  Rollno  Grade
1     kalyan      12    8.7
2  manikanta      34    9.0
3    kavitha      15    9.7

In [90]:
# Creating DataFrame using Dictionary
d = {'Names':['Durga','pavan','keerthi','chaitu'],'RollNumbers':[12,13,4,5],'Grade':['A','B','A','D']}
data = pd.DataFrame(d,index=np.arange(1,5))
data

Names  RollNumbers Grade
1    Durga           12     A
2    pavan           13     B
3  keerthi            4     A
4   chaitu            5     D

In [91]:
# Creating DataFrame using tuple
d = {'Names':('Durga','pavan','keerthi','chaitu'),'RollNumbers':(12,13,4,5),'Grade':('A','B','A','D')}
data = pd.DataFrame(d,index=np.arange(1,5))
data

Names  RollNumbers Grade
1    Durga           12     A
2    pavan           13     B
3  keerthi            4     A
4   chaitu            5     D

### Data Analysis & Data Manipulation

In [93]:
# Creating DataFrame using tuple
d = {'Names':('Durga','pavan','keerthi',''),'RollNumbers':(12,13,4,5),'Grade':('A','B','A','D')}
data = pd.DataFrame(d,index=np.arange(1,5))
data

Names  RollNumbers Grade
1    Durga           12     A
2    pavan           13     B
3  keerthi            4     A
4                     5     D

In [94]:
d = {'one':pd.Series([1,2,3,4],index = ['a','b','c','d']),
     'two':pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])}
data = pd.DataFrame(d)
data

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  NaN    5

In [110]:
data1 = data.values
print(data1)
print(data1.ndim)

[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]
 [ 4.  4.]
 [nan  5.]]
2


In [103]:
for i in data1:
    print(i[0])

1.0
2.0
3.0
4.0
nan


In [107]:
for i in data1:
    print(i[1])

1.0
2.0
3.0
4.0
5.0


In [105]:
data.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [111]:
data['one']['a']

1.0

In [112]:
data

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  NaN    5

In [113]:
data['two']['a']

1

In [114]:
data[0:3]

one  two
a  1.0    1
b  2.0    2
c  3.0    3

In [116]:
data[0:1]

one  two
a  1.0    1

In [117]:
data[-1:]

one  two
e  NaN    5