### Numpy
- Numpy : Numerical Python
- Numpy is a python Library used for working with arrays
- Numpy is faster than lists
- Used for scientific computing and data analysis

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [8]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(a1.ndim)
print(a1.shape)# array has 5 elements|columns 
print(a1.dtype)
print(a1.size)
print(a1.itemsize)

[1 2 3 4 5]
1
(5,)
int32
5
4


In [11]:
a2 = np.array([1.3,2.5,4.9])
print(a2.itemsize)
print(a2.size)

8
3


In [14]:
# 2D array
a2 = np.array([[1,2,3],[3,4,5],[6,7,2]])
print(a2)
print(a2.ndim)
print(a2.shape)# array has 3 rows and 3 columns
print(a2.dtype)
print(a2.size)
print(a2.itemsize)

[[1 2 3]
 [3 4 5]
 [6 7 2]]
2
(3, 3)
int32
9
4


In [16]:
# 3D array
a3 = np.array([[[1,2],[3,4],[2,3],[5,6]]])
print(a3)
print(a3.ndim)
print(a3.shape)# array has 1 layer, 4 rows and 2 columns
print(a3.dtype)
print(a3.size)
print(a3.itemsize)

[[[1 2]
  [3 4]
  [2 3]
  [5 6]]]
3
(1, 4, 2)
int32
8
4


In [18]:
a3 = np.array([[[1,2],[3,4]],[[2,3],[5,6]]])
print(a3)
print(a3.shape)

[[[1 2]
  [3 4]]

 [[2 3]
  [5 6]]]
(2, 2, 2)


### Create an array using range()
    - np.array(range(start,end,step))
    - np.array(range(start,end,step)).reshape(rows,columns)

In [26]:
a1 = np.array(range(15))
print(a1)
print(a1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
1


In [28]:
a2 = np.array(range(20)).reshape(2,10)
print(a2)
print(a2.ndim)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
2


In [29]:
a3 = np.array(range(15)).reshape(1,3,5)
print(a3)
print(a3.ndim)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
3


In [31]:
print(a3.reshape(1,15))
print(a3.reshape(5,3))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [33]:
a3 = np.array(range(12)).reshape(2,2,3)
print(a3)
print(a3.ndim)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3


In [34]:
a3 = np.array(range(1,20,2))
print(a3)

[ 1  3  5  7  9 11 13 15 17 19]


### Create an array using arange()
   - np.arange(start,end,step)

In [35]:
a1 = np.arange(12)
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
a1 = np.arange(12).reshape(4,3)
print(a1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [37]:
a1 = np.arange(12).reshape(1,4,3)
print(a1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


### Create an array using linspace() method
- Syntax : np.linspace(start,end,length of an array)

In [40]:
a1=np.linspace(1,20,10) # Both limits are inclusive
print(a1)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [44]:
a1 = np.linspace(1,100)
print(a1)
print(a1.ndim)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
1


In [45]:
print(a1.reshape(2,25))

[[  1.           3.02040816   5.04081633   7.06122449   9.08163265
   11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
   21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
   31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
   41.40816327  43.42857143  45.44897959  47.46938776  49.48979592]
 [ 51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
   61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
   71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
   81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
   91.91836735  93.93877551  95.95918367  97.97959184 100.        ]]


### Creating an array with Zeros, Ones and full
- np.zero(shape,dtype)
- np.ones(shape,dtype)
- np.full(shape,value)

In [47]:
# zeros matrix
z = np.zeros((5,5))
print(z)
print(type(z[0][0]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'numpy.float64'>


In [50]:
z = np.zeros((5,5),dtype=int)
print(z)
print(type(z[0][0]))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
<class 'numpy.int32'>


In [51]:
z*5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [55]:
o = np.ones((3,3))
print(o)
print(type(o[0][1]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.float64'>


In [56]:
o = np.ones((3,3),dtype=int)
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [57]:
o*6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [58]:
o+3

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [59]:
f = np.full((5,5),7)
print(f)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [60]:
np.diag(f)

array([7, 7, 7, 7, 7])

In [63]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
print(np.diag(a))

[1 5 9]


In [67]:
a[0][0] = 13

In [68]:
print(a)

[[13 13  3]
 [ 4  5  6]
 [ 7  8  9]]


In [69]:
a[1][1]=30

In [70]:
print(a)

[[13 13  3]
 [ 4 30  6]
 [ 7  8  9]]


In [71]:
print(np.diag(a))

[13 30  9]


In [74]:
# Identity matrix
a1 = np.eye(4,dtype=int)

In [75]:
a1

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [76]:
a1 = np.eye(4,3,dtype=int)
print(a1)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [79]:
class ClassA:
    a,b = 5,3
    def display():
        print('I am from ClassA')
class ClassB(ClassA):
    c,d = 6,2
    def show():
        print('I am from ClassB')
        
obj = ClassB
obj.show()
obj.display()
print(obj.b)

I am from ClassB
I am from ClassA
3


In [4]:
class Person:
    def __init__(self,name,occup,salary):
        self.name=name
        self.occup=occup
        self.salary=salary
    def details(self):
        print("Name :",self.name)
        print("Occup :",self.occup)
        print("Salary :",self.salary)
        
obj = Person('Pavan','Student',30000)
obj.details()

Name : Pavan
Occup : Student
Salary : 30000
